name: GitHub Pages 간단 배포

on:
  push:
    branches: [ main ]
    paths:
      - 'main.html'
      - 'style.css'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 체크아웃
        uses: actions/checkout@v4
        
      - name: 배포 파일 준비
        run: |
          mkdir -p deploy
          cp main.html deploy/index.html
          cp main.html deploy/main.html
          cp style.css deploy/style.css
          ls -la deploy/
        
      - name: GitHub Pages 배포
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./deploy
          enable_jekyll: false